name: CI
on:
  push:
    branches: [main, dev, cut-cookie]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  notebooks:
    name: Notebooks
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install ghostscript
      - run: python3 -m pip install pandas seaborn jupyter tqdm teeplot iterpop nbmetalog scipy nbconvert
      - uses: actions/checkout@v3
      - run: cd notebooks && ./execute_notebooks.sh
      # adapted from https://unix.stackexchange.com/a/545630
      - run: find -type f -name "*.pdf" -exec bash -c 'gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dBATCH -dQUIET -sOutputFile="new.pdf" "{}"; rm "{}"; mv "new.pdf" "{}";' {} \;
      - run: git init
      - uses: fregante/setup-git-user@v1
      - run: git commit --allow-empty -m "Initial commit"
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: notebooks # The branch the action should deploy to.
          folder: notebooks # The folder the action should deploy.
