name: CI
on:
  push:
    branches: [main, dev, cut-cookie]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  notebooks:
    name: Notebooks
    runs-on: ubuntu-20.04
    steps:
      # - run: |
      #    sudo echo 'Acquire::http::Timeout "60";' >> "/etc/apt/apt.conf.d/99timeout"
      #    sudo echo 'Acquire::ftp::Timeout "60";' >> "/etc/apt/apt.conf.d/99timeout"
      #    sudo echo 'Acquire::Retries "100";' >> "/etc/apt/apt.conf.d/99timeout"
      - run: sudo apt-get update
      - run: sudo apt-get install ghostscript
      - run: python3 -m pip install --no-cache-dir --timeout 60 --retries 100 pandas seaborn jupyter tqdm teeplot iterpop nbmetalog scipy nbconvert statsmodels
      - uses: actions/checkout@v3
      - run: cd notebooks && ./execute_notebooks.sh
      - run: git init
      - uses: fregante/setup-git-user@v1
      - run: git commit --allow-empty -m "Initial commit"
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: notebooks # The branch the action should deploy to.
          folder: notebooks # The folder the action should deploy.
